cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2017           # [win]
c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2017           # [win]
vc:
  - 14
python:
  - 3.7
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]
channel_sources:
  - conda-forge/label/llvm_rc,conda-forge,defaults
channel_targets:
  - conda-forge llvm_rc
