travis:
  secure:
    BINSTAR_TOKEN: IE6uUXGQI8Gu8Hs6Y2QRia2o6lldXHRY1UZ/VRUTvXK+ThyAgvhplJsowkXyNNmnuX/A0dKumq/waPTL/e575b44Y8w6JL8U/+mAv0imcko9YP4CSxcKzqoqjUNf68TuPwUbXNrE0hzCpp3K7clM0LjUHX3a2Fm3tnf0HO4b5mMS0JPvPhn5N+ytaDOd4Tn2951vrjLOikBGcEZMfa59McHXtkPm0g48/wHH0fnlY2wIt04EPMbSo6wfnnuH1E1zKZnLXfX+1KysNScJCf7GP4OMc5eUa17hoPMVlvBDeLroRasUomfx7UrrksfSTitoW30bCNXoEpD7YKosXROvqS8dnbpWsHjdmWpDTl8rrGrDoBsKdXVHlJKU6NcfLgrS+v4dXG++iJiw/6//3aNe+59aiqrHxvth+fsbPuu3P9sfe/RsSoRfUZJbNkmOZWPFOFstyRCyWq28kHIS3TDPQUzkQ2h1K7HSVMajxcGEhXffng9XIRhmhlzADhW6iAPeXXaRRasuTLCisHPwn1IEefCf0PVLuG1UN1ONGUbV+Rj+pbaQVMH3e7ySIMrfaBnGUZJuSOrPOwfxxtJeLdBsZEhY9zo/VKYOhOiFcGWBATCEogtwnlDYgZ871DwvKF3iyyIi/k0FcbG5iUqZaWqUWSrlekt/nnvWlSyQ2BXMcU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
